name: Spread
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  snap-build:
    runs-on: [self-hosted, large, jammy, X64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build devpack
        id: devpack-for-spring
        uses: snapcore/action-build@v1
        with:
          path: devpack-for-spring
      - name: Upload Snap to workflow artifacts
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: devpack-for-spring
          path: ${{ steps.devpack-for-spring.outputs.snap }}
      - name: Build manifest
        id: devpack-for-spring-manifest
        uses: snapcore/action-build@v1
        with:
          path: devpack-for-spring-manifest
      - name: Upload Snap to workflow artifacts
        id: upload-artifact-manifest
        uses: actions/upload-artifact@v4
        with:
          name: devpack-for-spring-manifest
          path: ${{ steps.devpack-for-spring-manifest.outputs.snap }}

  snap-tests:
    runs-on: [self-hosted, large, jammy, X64]
    needs: [snap-build]

    steps:
      - name: Cleanup job workspace
        run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Download snap artifact
        uses: actions/download-artifact@v4
        with:
          name: devpack-for-spring-manifest
          path: devpack-for-spring-manifest
      - name: Download snap artifact
        uses: actions/download-artifact@v4
        with:
          name: devpack-for-spring
          path: devpack-for-spring

      - uses: actions/checkout@v4
        with:
          repository: snapcore/spread
          path: _spread

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'

      - name: Install LXD
        uses: canonical/setup-lxd@v0.1.1
        with:
            channel: 5.21/stable

      - name: Run spread
        run: |
          (cd _spread/cmd/spread && go build)
          _spread/cmd/spread/spread

      - name: Discard spread workers
        if: always()
        run: |
          shopt -s nullglob
          for r in .spread-reuse.*.yaml; do
            spread -discard -reuse-pid="$(echo "$r" | grep -o -E '[0-9]+')"
          done
